#!/usr/bin/env ruby

require File.expand_path('../../../../../config/environment.rb', __FILE__)

file_name = ARGV.shift

if file_name.nil? then
  puts "Usage: #{$0} file_name"
  exit 1
end

importer = Logjam::FileImporter.new file_name
importer.process

