#!/usr/bin/env ruby

require File.expand_path(File.dirname(__FILE__)+'/../../../../config/environment.rb')

config_name = ARGV.first

puts "Starting amqp importer for config '#{config_name}'"

trap("INT") do
  puts "Stopping event loop"
  @amqp_importer.stop
end

@amqp_importer = Logjam::AMQPImporter.new(config_name)
@amqp_importer.process
