#!/usr/bin/env ruby

$stdout.sync = true
$stderr.sync = true

require File.expand_path('../../../../../config/environment.rb', __FILE__)

config_name = ARGV.first
profile = ARGV[1..-1].include?('--profile')

puts "LJ[#{$$}]: Starting amqp importer for config '#{config_name}'"

if profile
  require 'ruby-prof'
  measure_mode = "WALL_TIME"
  ARGV.each{|arg| measure_mode=$1.upcase if arg =~ /--measure_mode=([^ ]*)/ }
  if %w(PROCESS_TIME WALL_TIME CPU_TIME ALLOCATIONS MEMORY).include?(measure_mode)
    RubyProf.measure_mode = RubyProf.const_get measure_mode
  else
    $stderr.puts "LJ[#{$$}]: unsupported ruby_prof measure mode: #{measure_mode}"
    RubyProf.measure_mode = RubyProf::WALL_TIME
  end
  RubyProf.start

  at_exit do
    result = RubyProf.stop
    printer = RubyProf::MultiPrinter.new(result)
    printer.print(:path => "#{Rails.root}",
                  :profile => "importer-profile-#{config_name}",
                  :min_percent => 0.1,
                  :threshold => 1,
                  :title => "logjam importer benchmark: #{config_name}")
    system("open #{printer.stack_profile}") if RUBY_PLATFORM =~ /darwin/
  end
end

# GC.enable_stats
# GC.enable_trace
stream = Logjam.streams[config_name]
importer = Logjam::ImporterManager.new(stream)
importer.process

