#!/usr/bin/env ruby

require File.expand_path(File.dirname(__FILE__)+'/../../../../config/environment.rb')

config_name = ARGV.first
cluster = ARGV.second

puts "Starting amqp log parser for '#{config_name}'"

trap("INT") do
  puts "Stopping event loop"
  @amqp_log_parser.stop
end

@amqp_log_parser = Logjam::AMQPLogParser.new(config_name, cluster)
@amqp_log_parser.process
