#!/usr/bin/env ruby

require File.expand_path(File.dirname(__FILE__)+'/../../../../config/environment.rb')

application = ARGV.first

puts "Starting amqp log parser for rails environment '#{RAILS_ENV}'"

trap("INT") do
  puts "Stopping event loop"
  @amqp_log_parser.stop
end

@amqp_log_parser = Logjam::AMQPLogParser.new(application)
@amqp_log_parser.process
