#!/usr/bin/env ruby

require_relative '../../../config/environment'

config_name = ARGV.first
file_name = ARGV.second

puts "Starting file replayer '#{config_name}'"

Logjam::FileReplayer.new(config_name, file_name).process
