#!/bin/bash
# limit open files
# ulimit -n 12345
# limit resident size to 5 GB, which is plenty
# ulimit -m 5000000
exec 2>&1
if [ -x /opt/logjam/bin/logjam-importer ]; then
  importer=/opt/logjam/bin/logjam-importer
else
  importer=/usr/local/bin/logjam-importer
fi
exec $importer -c LOGJAM_SERVICE_TARGET_DIR/cimporter.conf "$@"
